Create color.java
FTC-12510-Gigabyte/Basic-Template pull request #2
Opened 2017-12-08 20:02 UTC by noampro

Before issuing a pull request, please see the contributing page.

2017-12-08 21:44 UTC, orike122 requested changes
בקיצור, כל הכבוד על העבודה ועל השימוש בגיט.
צריך לעשות קצת תיקונים ואז הכל יהיה טוב.
אם אתה מסתבך או לא יודע איך לעשות משהו תרגיש חופשי לפנות אלי.

2017-12-08 21:44 UTC, orike122 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/color.java
> +@TeleOp(name = "Calibrate MR Color", group = "Utilities")
עדיף לתת שם יותר ברור

2017-12-08 21:44 UTC, orike122 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/color.java
> +    public int command;
לא הבנתי מה זה

2017-12-08 21:44 UTC, orike122 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/color.java
> +    public int init(int a) {
הפעולה צריכה להחזיר וויד לא אינט.
בנוסף אל תשכח להוסיף אוברייד
אין סיבה לקבל פרמטר בפונקציה

2017-12-08 21:44 UTC, orike122 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/color.java
> +    public void loop() {
עדיף להגדיר את כל הקבועים שמסמנים צבעים ודברים נוספים כפרייווט בתחילת המחלקה ולא בתוך פונקציה. עוד רעיון זה להוסיף מחלקה שתכיל קבועים סטטיים בתוכה וכך נוכל להשתמש בקבועים אלו בכל מקום, תדבר איתי ואני אסביר לך בצורה יותר מפורטת.

2017-12-09 10:03 UTC, noampro commented
אני כתבתי את זה עם דוד שלי ועשינו רק דוגמא אני ישנה את זה איתכם כדי שנמשיך
ביחד תודה על ההערות
אני אשמח אם תאשר את הקוד

נועם

2017-12-08 23:44 GMT+02:00 orike122 <notifications@github.com>:

> *@orike122* requested changes on this pull request.
>
> בקיצור, כל הכבוד על העבודה ועל השימוש בגיט.
> צריך לעשות קצת תיקונים ואז הכל יהיה טוב.
> אם אתה מסתבך או לא יודע איך לעשות משהו תרגיש חופשי לפנות אלי.
> ------------------------------
>
> In TeamCode/src/main/java/org/firstinspires/ftc/teamcode/color.java
> <https://github.com/FTC-12510-Gigabyte/Basic-Template/pull/2#discussion_r155880838>
> :
>
> > + * This code allows a user -- with the help of a gamepad -- calibrate a Modern Robotics I2C sensor
> + * sensor for both black and white states. Instructions for completing the calibration are included
> + * in the driver's station telemetry.
> + *
> + * Although Modern Robotics recommends the calibration steps written in the instructions, this may
> + * not be best for all uses. A team could choose, for example, to calibrate black as a slightly
> + * illuminated dark grey floor tile and white as slightly illuminated white gaffer's tape. After
> + * every calibration, it is a good idea to check the thresholds used in other OpModes to see if
> + * they are still correct.
> + *
> + * Use this code at your own risk. You should always (1) use proper safety attire, (2) test your
> + * code before using it in a situation that could harm someone, and (3) make sure you understand
> + * what a piece of code (including this one) does before running it.
> + */
> +
> +@TeleOp(name = "Calibrate MR Color", group = "Utilities")
>
> עדיף לתת שם יותר ברור
> ------------------------------
>
> In TeamCode/src/main/java/org/firstinspires/ftc/teamcode/color.java
> <https://github.com/FTC-12510-Gigabyte/Basic-Template/pull/2#discussion_r155880925>
> :
>
> > +
> +@TeleOp(name = "Calibrate MR Color", group = "Utilities")
> +@Disabled
> +public class CalibrateColorSensor extends OpMode {
> +
> +    // Color Sensor to calibrate. Require that it is a Modern Robotics sensor.
> +    private ModernRoboticsI2cColorSensor sensor;
> +
> +    // Track whether a calibration was recently requested.
> +
> +
> +    /**
> +     * Initialize sensor sensor hardware.
> +     */
> +
> +    public int command;
>
> לא הבנתי מה זה
> ------------------------------
>
> In TeamCode/src/main/java/org/firstinspires/ftc/teamcode/color.java
> <https://github.com/FTC-12510-Gigabyte/Basic-Template/pull/2#discussion_r155881159>
> :
>
> > +@Disabled
> +public class CalibrateColorSensor extends OpMode {
> +
> +    // Color Sensor to calibrate. Require that it is a Modern Robotics sensor.
> +    private ModernRoboticsI2cColorSensor sensor;
> +
> +    // Track whether a calibration was recently requested.
> +
> +
> +    /**
> +     * Initialize sensor sensor hardware.
> +     */
> +
> +    public int command;
> +
> +    public int init(int a) {
>
> הפעולה צריכה להחזיר וויד לא אינט.
> בנוסף אל תשכח להוסיף אוברייד
> אין סיבה לקבל פרמטר בפונקציה
> ------------------------------
>
> In TeamCode/src/main/java/org/firstinspires/ftc/teamcode/color.java
> <https://github.com/FTC-12510-Gigabyte/Basic-Template/pull/2#discussion_r155881896>
> :
>
> > +    public int command;
> +
> +    public int init(int a) {
> +        // Change the value "sensor" to the name of your sensor sensor.
> +        sensor = hardwareMap.get(ModernRoboticsI2cColorSensor.class, "sensor");
> +    }
> +
> +    /**
> +     * Respond to gamepad input to perform calibrations.
> +     *
> +     * As explained in the prompt, X will begin a black-level calibration, and Y will begin a
> +     * white-level calibration. We prevent calibrations from being triggered within one second
> +     * of one another using a timer.
> +     */
> +    @Override
> +    public void loop() {
>
> עדיף להגדיר את כל הקבועים שמסמנים צבעים ודברים נוספים כפרייווט בתחילת
> המחלקה ולא בתוך פונקציה. עוד רעיון זה להוסיף מחלקה שתכיל קבועים סטטיים
> בתוכה וכך נוכל להשתמש בקבועים אלו בכל מקום, תדבר איתי ואני אסביר לך בצורה
> יותר מפורטת.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/FTC-12510-Gigabyte/Basic-Template/pull/2#pullrequestreview-82279984>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AgRJaTp00lf_51I7UJ048Gb77oUDoHhqks5s-a2ngaJpZM4Q7k_u>
> .
>

2017-12-09 16:05 UTC, orike122 commented
סבבה, אני אאשר, רק שתדע שאם אתה רוצה להעלות משהו. אתה יכול לעשות push במקום pull request

2017-12-11 13:41 UTC, merged